package xiaozhi.modules.agent.dto;

import java.io.Serializable;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import lombok.Data;

/**
 * AgentCreateDTO
 * specialUsed forNewaddAgent，notContainid、agentCodeandsortField，These fields are automatically generated by the system/SetDefault value
 */
@Data
@Schema(description = "AgentCreateObject")
public class AgentCreateDTO implements Serializable {
    private static final long serialVersionUID = 1L;

    @Schema(description = "Agent name", example = "Customer service assistant")
    @NotBlank(message = "Agent namecannot be empty")
    private String agentName;
}