-- This file initializes model provider data automatically on project startup
-- --------------------------------------------------------
-- Initialize model provider data
DELETE FROM `ai_model_provider`;
INSERT INTO `ai_model_provider` (`id`, `model_type`, `provider_code`, `name`, `fields`, `sort`, `creator`, `create_date`, `updater`, `update_date`) VALUES
-- VAD model provider
('SYSTEM_VAD_SileroVAD', 'VAD', 'silero', 'SileroVAD Voice Activity Detection', '[{"key":"threshold","label":"Detection threshold","type":"number"},{"key":"model_dir","label":"Model directory","type":"string"},{"key":"min_silence_duration_ms","label":"Minimum silence duration","type":"number"}]', 1, 1, NOW(), 1, NOW()),

-- ASR model provider
('SYSTEM_ASR_FunASR', 'ASR', 'fun_local', 'FunASR Speech Recognition', '[{"key":"model_dir","label":"Model directory","type":"string"},{"key":"output_dir","label":"Output directory","type":"string"}]', 1, 1, NOW(), 1, NOW()),
('SYSTEM_ASR_SherpaASR', 'ASR', 'sherpa_onnx_local', 'SherpaASR Speech Recognition', '[{"key":"model_dir","label":"Model directory","type":"string"},{"key":"output_dir","label":"Output directory","type":"string"}]', 2, 1, NOW(), 1, NOW()),
('SYSTEM_ASR_DoubaoASR', 'ASR', 'doubao', 'Volcengine Speech Recognition', '[{"key":"appid","label":"App ID","type":"string"},{"key":"access_token","label":"Access Token","type":"string"},{"key":"cluster","label":"Cluster","type":"string"},{"key":"output_dir","label":"Output directory","type":"string"}]', 3, 1, NOW(), 1, NOW()),

-- LLM model provider
('SYSTEM_LLM_openai', 'LLM', 'openai', 'OpenAI API', '[{"key":"base_url","label":"Base URL","type":"string"},{"key":"model_name","label":"Model name","type":"string"},{"key":"api_key","label":"API Key","type":"string"},{"key":"temperature","label":"Temperature","type":"number"},{"key":"max_tokens","label":"Max tokens","type":"number"},{"key":"top_p","label":"top_p value","type":"number"},{"key":"top_k","label":"top_k value","type":"number"},{"key":"frequency_penalty","label":"Frequency penalty","type":"number"}]', 1, 1, NOW(), 1, NOW()),
('SYSTEM_LLM_AliBL', 'LLM', 'AliBL', 'Aliyun Bailian API', '[{"key":"base_url","label":"Base URL","type":"string"},{"key":"app_id","label":"App ID","type":"string"},{"key":"api_key","label":"API Key","type":"string"},{"key":"is_no_prompt","label":"Do not use local prompt","type":"boolean"},{"key":"ali_memory_id","label":"Memory ID","type":"string"}]', 2, 1, NOW(), 1, NOW()),
('SYSTEM_LLM_ollama', 'LLM', 'ollama', 'Ollama API', '[{"key":"model_name","label":"Model name","type":"string"},{"key":"base_url","label":"Service address","type":"string"}]', 3, 1, NOW(), 1, NOW()),
('SYSTEM_LLM_dify', 'LLM', 'dify', 'Dify API', '[{"key":"base_url","label":"Base URL","type":"string"},{"key":"api_key","label":"API Key","type":"string"},{"key":"mode","label":"Conversation mode","type":"string"}]', 4, 1, NOW(), 1, NOW()),
('SYSTEM_LLM_gemini', 'LLM', 'gemini', 'Gemini API', '[{"key":"api_key","label":"API Key","type":"string"},{"key":"model_name","label":"Model name","type":"string"},{"key":"http_proxy","label":"HTTP Proxy","type":"string"},{"key":"https_proxy","label":"HTTPS Proxy","type":"string"}]', 5, 1, NOW(), 1, NOW()),
('SYSTEM_LLM_coze', 'LLM', 'coze', 'Coze API', '[{"key":"bot_id","label":"Bot ID","type":"string"},{"key":"user_id","label":"User ID","type":"string"},{"key":"personal_access_token","label":"Personal access token","type":"string"}]', 6, 1, NOW(), 1, NOW()),
('SYSTEM_LLM_fastgpt', 'LLM', 'fastgpt', 'FastGPT API', '[{"key":"base_url","label":"Base URL","type":"string"},{"key":"api_key","label":"API Key","type":"string"},{"key":"variables","label":"Variable","type":"dict","dict_name":"variables"}]', 7, 1, NOW(), 1, NOW()),
('SYSTEM_LLM_xinference', 'LLM', 'xinference', 'Xinference API', '[{"key":"model_name","label":"Model name","type":"string"},{"key":"base_url","label":"Service address","type":"string"}]', 8, 1, NOW(), 1, NOW()),
('SYSTEM_LLM_doubao', 'LLM', 'doubao', 'Volcengine LLM', '[{"key":"base_url","label":"Base URL","type":"string"},{"key":"model_name","label":"Model name","type":"string"},{"key":"api_key","label":"API Key","type":"string"}]', 9, 1, NOW(), 1, NOW()),
('SYSTEM_LLM_chatglm', 'LLM', 'chatglm', 'ChatGLM API', '[{"key":"model_name","label":"Model name","type":"string"},{"key":"url","label":"Service address","type":"string"},{"key":"api_key","label":"API Key","type":"string"}]', 10, 1, NOW(), 1, NOW()),

-- TTS model provider
('SYSTEM_TTS_edge', 'TTS', 'edge', 'Edge TTS', '[{"key":"voice","label":"Voice","type":"string"},{"key":"output_dir","label":"Output directory","type":"string"}]', 1, 1, NOW(), 1, NOW()),
('SYSTEM_TTS_doubao', 'TTS', 'doubao', 'Volcengine TTS', '[{"key":"api_url","label":"API Address","type":"string"},{"key":"voice","label":"Voice","type":"string"},{"key":"output_dir","label":"Output directory","type":"string"},{"key":"authorization","label":"Authorization","type":"string"},{"key":"appid","label":"App ID","type":"string"},{"key":"access_token","label":"Access Token","type":"string"},{"key":"cluster","label":"Cluster","type":"string"}]', 2, 1, NOW(), 1, NOW()),
('SYSTEM_TTS_siliconflow', 'TTS', 'siliconflow', 'SiliconFlow TTS', '[{"key":"model","label":"Model","type":"string"},{"key":"voice","label":"Voice","type":"string"},{"key":"output_dir","label":"Output directory","type":"string"},{"key":"access_token","label":"Access Token","type":"string"},{"key":"response_format","label":"Response format","type":"string"}]', 3, 1, NOW(), 1, NOW()),
('SYSTEM_TTS_cozecn', 'TTS', 'cozecn', 'COZECN TTS', '[{"key":"voice","label":"Voice","type":"string"},{"key":"output_dir","label":"Output directory","type":"string"},{"key":"access_token","label":"Access Token","type":"string"},{"key":"response_format","label":"Response format","type":"string"}]', 4, 1, NOW(), 1, NOW()),
('SYSTEM_TTS_fishspeech', 'TTS', 'fishspeech', 'FishSpeech TTS', '[{"key":"output_dir","label":"Output directory","type":"string"},{"key":"response_format","label":"Response format","type":"string"},{"key":"reference_id","label":"Reference ID","type":"string"},{"key":"reference_audio","label":"Reference audio","type":"dict","dict_name":"reference_audio"},{"key":"reference_text","label":"Reference text","type":"dict","dict_name":"reference_text"},{"key":"normalize","label":"Standardize","type":"boolean"},{"key":"max_new_tokens","label":"Max new tokens","type":"number"},{"key":"chunk_length","label":"Chunk length","type":"number"},{"key":"top_p","label":"top_p value","type":"number"},{"key":"repetition_penalty","label":"Repetition penalty","type":"number"},{"key":"temperature","label":"Temperature","type":"number"},{"key":"streaming","label":"Streaming mode","type":"boolean"},{"key":"use_memory_cache","label":"Use memory cache","type":"string"},{"key":"seed","label":"Seed","type":"number"},{"key":"channels","label":"Channels","type":"number"},{"key":"rate","label":"Sample rate","type":"number"},{"key":"api_key","label":"API Key","type":"string"},{"key":"api_url","label":"API Address","type":"string"}]', 5, 1, NOW(), 1, NOW()),
('SYSTEM_TTS_gpt_sovits_v2', 'TTS', 'gpt_sovits_v2', 'GPT-SoVITS V2', '[{"key":"url","label":"Service address","type":"string"},{"key":"output_dir","label":"Output directory","type":"string"},{"key":"text_lang","label":"TextLanguages","type":"string"},{"key":"ref_audio_path","label":"Reference audio path","type":"string"},{"key":"prompt_text","label":"Prompt text","type":"string"},{"key":"prompt_lang","label":"PromptLanguages","type":"string"},{"key":"top_k","label":"top_k value","type":"number"},{"key":"top_p","label":"top_p value","type":"number"},{"key":"temperature","label":"Temperature","type":"number"},{"key":"text_split_method","label":"Text splitting method","type":"string"},{"key":"batch_size","label":"Batch size","type":"number"},{"key":"batch_threshold","label":"Batch processing threshold","type":"number"},{"key":"split_bucket","label":"Enable bucketing","type":"boolean"},{"key":"return_fragment","label":"Return fragments","type":"boolean"},{"key":"speed_factor","label":"Speed factor","type":"number"},{"key":"streaming_mode","label":"Streaming mode","type":"boolean"},{"key":"seed","label":"Seed","type":"number"},{"key":"parallel_infer","label":"Parallel inference","type":"boolean"},{"key":"repetition_penalty","label":"Repetition penalty","type":"number"},{"key":"aux_ref_audio_paths","label":"AuxiliaryReference audio path","type":"dict","dict_name":"aux_ref_audio_paths"}]', 6, 1, NOW(), 1, NOW()),
('SYSTEM_TTS_gpt_sovits_v3', 'TTS', 'gpt_sovits_v3', 'GPT-SoVITS V3', '[{"key":"url","label":"Service address","type":"string"},{"key":"output_dir","label":"Output directory","type":"string"},{"key":"text_language","label":"TextLanguages","type":"string"},{"key":"refer_wav_path","label":"Reference audio path","type":"string"},{"key":"prompt_language","label":"PromptLanguages","type":"string"},{"key":"prompt_text","label":"Prompt text","type":"string"},{"key":"top_k","label":"top_k value","type":"number"},{"key":"top_p","label":"top_p value","type":"number"},{"key":"temperature","label":"Temperature","type":"number"},{"key":"cut_punc","label":"Split punctuation","type":"string"},{"key":"speed","label":"Speed","type":"number"},{"key":"inp_refs","label":"Input reference","type":"dict","dict_name":"inp_refs"},{"key":"sample_steps","label":"Sample steps","type":"number"},{"key":"if_sr","label":"Use SR","type":"boolean"}]', 7, 1, NOW(), 1, NOW()),
('SYSTEM_TTS_minimax', 'TTS', 'minimax', 'Minimax TTS', '[{"key":"output_dir","label":"Output directory","type":"string"},{"key":"group_id","label":"Group ID","type":"string"},{"key":"api_key","label":"API Key","type":"string"},{"key":"model","label":"Model","type":"string"},{"key":"voice_id","label":"Voice ID","type":"string"}]', 8, 1, NOW(), 1, NOW()),
('SYSTEM_TTS_aliyun', 'TTS', 'aliyun', 'Alibaba CloudTTS', '[{"key":"output_dir","label":"Output directory","type":"string"},{"key":"appkey","label":"App Secret","type":"string"},{"key":"token","label":"Access Token","type":"string"},{"key":"voice","label":"Voice","type":"string"},{"key":"access_key_id","label":"Access Key ID","type":"string"},{"key":"access_key_secret","label":"Access KeyPassword","type":"string"}]', 9, 1, NOW(), 1, NOW()),
('SYSTEM_TTS_ttson', 'TTS', 'ttson', 'ACGNTTS', '[{"key":"token","label":"Access Token","type":"string"},{"key":"voice_id","label":"Voice ID","type":"string"},{"key":"speed_factor","label":"Speed factor","type":"number"},{"key":"pitch_factor","label":"Pitch factor","type":"number"},{"key":"volume_change_dB","label":"Volume change","type":"number"},{"key":"to_lang","label":"TargetLanguages","type":"string"},{"key":"url","label":"Service address","type":"string"},{"key":"format","label":"Format","type":"string"},{"key":"output_dir","label":"Output directory","type":"string"},{"key":"emotion","label":"Emotion","type":"number"}]', 10, 1, NOW(), 1, NOW()),
('SYSTEM_TTS_openai', 'TTS', 'openai', 'OpenAI TTS', '[{"key":"api_key","label":"API Key","type":"string"},{"key":"api_url","label":"API Address","type":"string"},{"key":"model","label":"Model","type":"string"},{"key":"voice","label":"Voice","type":"string"},{"key":"speed","label":"Speed","type":"number"},{"key":"output_dir","label":"Output directory","type":"string"}]', 11, 1, NOW(), 1, NOW()),
('SYSTEM_TTS_custom', 'TTS', 'custom', 'CustomTTS', '[{"key":"url","label":"Service address","type":"string"},{"key":"params","label":"Request parameters","type":"dict","dict_name":"params"},{"key":"headers","label":"Request headers","type":"dict","dict_name":"headers"},{"key":"format","label":"Audio format","type":"string"},{"key":"output_dir","label":"Output directory","type":"string"}]', 12, 1, NOW(), 1, NOW()),
('SYSTEM_TTS_302ai', 'TTS', '302ai', '302AI TTS', '[{"key":"api_url","label":"API Address","type":"string"},{"key":"authorization","label":"Authorization","type":"string"},{"key":"voice","label":"Voice","type":"string"},{"key":"output_dir","label":"Output directory","type":"string"},{"key":"access_token","label":"Access Token","type":"string"}]', 13, 1, NOW(), 1, NOW()),
('SYSTEM_TTS_gizwits', 'TTS', 'gizwits', 'GizwitsTTS', '[{"key":"api_url","label":"API Address","type":"string"},{"key":"authorization","label":"Authorization","type":"string"},{"key":"voice","label":"Voice","type":"string"},{"key":"output_dir","label":"Output directory","type":"string"},{"key":"access_token","label":"Access Token","type":"string"}]', 14, 1, NOW(), 1, NOW()),

-- Memory model provider
('SYSTEM_Memory_mem0ai', 'Memory', 'mem0ai', 'Mem0AIMemory', '[{"key":"api_key","label":"API Key","type":"string"}]', 1, 1, NOW(), 1, NOW()),
('SYSTEM_Memory_nomem', 'Memory', 'nomem', 'No Memory', '[]', 2, 1, NOW(), 1, NOW()),
('SYSTEM_Memory_mem_local_short', 'Memory', 'mem_local_short', 'Local Short Memory', '[]', 3, 1, NOW(), 1, NOW()),

-- Intent model provider
('SYSTEM_Intent_nointent', 'Intent', 'nointent', 'No Intent Recognition', '[]', 1, 1, NOW(), 1, NOW()),
('SYSTEM_Intent_intent_llm', 'Intent', 'intent_llm', 'LLMIntent Recognition', '[{"key":"llm","label":"LLM Model","type":"string"}]', 2, 1, NOW(), 1, NOW()),
('SYSTEM_Intent_function_call', 'Intent', 'function_call', 'Function call intent recognition', '[{"key":"functions","label":"Function list","type":"dict","dict_name":"functions"}]', 3, 1, NOW(), 1, NOW());
